FROM jenkins/jenkins:lts-jdk11

# install tools with root user
USER root
{% if Vars.Jenkins.apt_packages is defined %}
RUN apt-get update && apt-get install -y {% for apt_package in Vars.Jenkins.apt_packages %}{{ apt_package }} {% endfor %}
{% endif %}

{% if Vars.Jenkins.pip_packages is defined %}
RUN pip install {% for pip_package in Vars.Jenkins.pip_packages %}{{ pip_package }} {% endfor %}
{% endif %}

# drop back to the regular jenkins user
USER jenkins

ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
WORKDIR /var/jenkins_home

COPY security.groovy /usr/share/jenkins/ref/init.groovy.d/security.groovy
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt

# Installing Jenkins Plugins to Docker Jenkins
# https://stackoverflow.com/questions/29328278/installing-jenkins-plugins-to-docker-jenkins
RUN jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt
